[server]
port = 8000
ip = "0.0.0.0"
log_dir = "./logs"
# interval in seconds
config_refresh_interval = 5

[http]
max_http_header_size = 8192
# TODO to set up table of {...} codes for find / replace
server_name = "Frank's web server ({system}/{release})"
# list of additional http fields TODO setup table for this
fields = []

[resource]
resource_dir = "./www/"
default_page = "index.html"
# list of resources that are allowed to be modified by PUT, POST, PATCH and DELETE requests
# acl_file is for files/directories and acl_table is for entries in the route_table
acl_file = []
acl_table = []
# choose between "allow" - only the resources specified in acl_file and acl_table may be modified
# or "deny" - every resource but the ones specifed may be modified
acl_type = "allow"
# cache for requested resources
reponse_cache_enabled = true
# interval in seconds
cache_refresh_interval = 300
# table routing is priotitised over filesystem routing
fs_routing = true
table_routing = false
# list of inline tables?
route_table = [
    {}
]
# (fast) -> (small)
# gzip ranges from 1-9
# deflate ranges from 0-9
# ranges from 0-11
# ranges from -7-22
gzip_compression_level = 6
deflate_compression_level = 6
brotli_compression_level = 6
zstd_compression_level = 6
# defines both priority and supported compression schemas
compression_priority = ["br", "gzip", "identity", "deflate"]